### ISSUE TITLE
always tries to connect to localhost:3001

### ISSUE THREAD

**Issue by juliangruber** [geut/permanent-seeder#84]
I started the services according to the readme, and even tried to change the `dashboard/.env` to

```ini
PUBLIC_URL=http://46.101.192.138:3001/
EXTEND_ESLINT=true
```

But the dashboard still tries to connect to `localhost:3001`:

![image](https://user-images.githubusercontent.com/10247/92475030-090af180-f1dd-11ea-935d-5649985c3ef1.png)

I did an `npm run build` in the dashboard directory after changing the config, and then ran `cli/bin/run start --restart`.

**Comment by estebanprimost** [comment]
Hi @juliangruber, thanks for your catch! Can you try again with latest `master` branch, please? 
Remember to rebuild dashboard and restart services.

**Comment by juliangruber** [comment]
@estebanprimost Thanks! I did this:

```bash
cd permanent-seeder
git pull
cd packages/dashboard
npm run build
cd ../cli
./bin/run start --restart
```

and got this in the error log:

```
[2020-09-09T08:16:33.609Z] ERROR seeder-1599639393226/BROKER: Failed to load service '/root/permanent-seeder/packages/sdk/src/services/keys-updater.service.js' TypeError: Cannot read property 'map' of undefined
    at Service.created (/root/permanent-seeder/packages/sdk/src/services/keys-updater.service.js:56:28)
    at schema.created.forEach.fn (/root/permanent-seeder/node_modules/moleculer/src/service.js:215:41)
    at Array.forEach (<anonymous>)
    at Service._init (/root/permanent-seeder/node_modules/moleculer/src/service.js:215:24)
    at Service.parseServiceSchema (/root/permanent-seeder/node_modules/moleculer/src/service.js:188:8)
    at new Service (/root/permanent-seeder/node_modules/moleculer/src/service.js:63:9)
    at ServiceBroker.createService (/root/permanent-seeder/node_modules/moleculer/src/service-broker.js:805:14)
    at ServiceBroker.loadService (/root/permanent-seeder/node_modules/moleculer/src/service-broker.js:770:16)
    at serviceFiles.forEach.filename (/root/permanent-seeder/node_modules/moleculer/src/service-broker.js:724:42)
    at Array.forEach (<anonymous>)
TypeError: Cannot read property 'map' of undefined
    at Service.created (/root/permanent-seeder/packages/sdk/src/services/keys-updater.service.js:56:28)
    at schema.created.forEach.fn (/root/permanent-seeder/node_modules/moleculer/src/service.js:215:41)
    at Array.forEach (<anonymous>)
    at Service._init (/root/permanent-seeder/node_modules/moleculer/src/service.js:215:24)
    at Service.parseServiceSchema (/root/permanent-seeder/node_modules/moleculer/src/service.js:188:8)
    at new Service (/root/permanent-seeder/node_modules/moleculer/src/service.js:63:9)
    at ServiceBroker.createService (/root/permanent-seeder/node_modules/moleculer/src/service-broker.js:805:14)
    at ServiceBroker.loadService (/root/permanent-seeder/node_modules/moleculer/src/service-broker.js:770:16)
    at serviceFiles.forEach.filename (/root/permanent-seeder/node_modules/moleculer/src/service-broker.js:724:42)
    at Array.forEach (<anonymous>)
```

**Comment by estebanprimost** [comment]
Oh, you might reinitialize config with (you're going to loose your previous config): 

`./bin/run config:init --global --force`

LMK

**Comment by juliangruber** [comment]
I did

```bash
./bin/run config:init --global --force
./bin/run start --restart
```

but still the same error. Can I get you some more debug information another way?

**Comment by estebanprimost** [comment]
Hey @juliangruber! Still an old config problem, before we handle one endpoint (the Vault).

The problem comes from I think you have another config file probably in your CWD. We merge configs from `--global` (your home dir) and your CWD. The `cwd` one takes precedence over home folder. 

Some questions to debug:
- Have you restarted seeder after `config:init`? 
- Do you have múltiple `.toml` configs files?

To check what config is being used, please run: `./bin/run config:get` and it should be something like:

```json
{
  "security": {
    "secret": "----"
  },
  "keys": {
    "endpoints": [
      {
        "url": "http://localhost:3000",
        "frequency": 5,
        "hook": "/home/esteban/permanent-seeder/permanent-seeder-endpoint-hook.js"
      }
    ],
    "db": {
      "path": "/home/esteban/permanent-seeder/keys.db"
    }
  },
  "metrics": {
    "db": {
      "path": "/home/esteban/permanent-seeder/metrics.db"
    }
  }
}
```

And here is the `permanent-seeder.toml` config file :
```toml
[security]
secret = "----"

[[keys.endpoints]]
url = "http://localhost:3000"
frequency = 5
hook = "/home/esteban/permanent-seeder/permanent-seeder-endpoint-hook.js"

[keys.db]
path = "/home/esteban/permanent-seeder/keys.db"

[metrics.db]
path = "/home/esteban/permanent-seeder/metrics.db"
```

**Comment by juliangruber** [comment]
> * Have you restarted seeder after `config:init`?

I did

```
./bin/run config:init --global --force
./bin/run start --restart
```

Does that qualify as restarting the seeder?

```bash
./bin/run config:get
{
  "security": {
    "secret": "..."
  },
  "keys": {
    "endpoints": [
      {
        "url": "http://localhost:3000",
        "frequency": 5,
        "hook": "/root/permanent-seeder/permanent-seeder-endpoint-hook.js"      
      }
    ],
    "db": {
      "path": "/root/permanent-seeder/keys.db"
    }
  },
  "metrics": {
    "db": {
      "path": "/root/permanent-seeder/metrics.db"
    }
  }
}
```

> And here is the `permanent-seeder.toml` config file :

```toml
[security]
secret = "..."

[[keys.endpoints]]
url = "http://localhost:3000"
frequency = 5
hook = "/root/permanent-seeder/permanent-seeder-endpoint-hook.js"

[keys.db]
path = "/root/permanent-seeder/keys.db"

[metrics.db]
path = "/root/permanent-seeder/metrics.db"
```

**Comment by juliangruber** [comment]
I think this also shows it would be handy to have upgrade instructions, for what to do after a `git pull` of the repository

**Comment by dpaez** [comment]
@juliangruber yeah, some upgrade docs would be super handy. We still need to tackle down the docs revamp task, so I'm going to be sure to add some upgrade section if you are using install from github. 

We plan to release this week (that can explain also this "breaking" config change for example) and I'm thinking that we can do a "_beta_" release first and after a few days with more usage by others we can remove the beta tag.

**Comment by estebanprimost** [comment]
> Does that qualify as restarting the seeder?

yes

Ok with that config it should work now, but you might want to hard reset everything by:
- Removing folder `/root/permanent-seeder`
- Remove any local `permanent-seeder.toml`, `keys.db` and `metrics.db` file (if any)

> I think this also shows it would be handy to have upgrade instructions, for what to do after a git pull of the repository

Agree with that, thanks for the suggestion. We are currently on a pre-release with some breaking changes. Hope to finish soon.

**Comment by dpaez** [comment]
Also, after the upgrade the error logs still outputs the same thing you pasted before? or has it changed?

**Comment by juliangruber** [comment]
I'm getting this now after a fresh install:

```bash
root@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/permanent-seeder/packages/cli# ./bin/run config:init
(node:327728) [ENOENT] Error: spawn permanent-seeder ENOENT
```

I executed all the steps from the readme before that

**Comment by dpaez** [comment]
I think that this last error might be related to our config update. We renamed the config file and discarded the <cwd>/config usage.

The config now lives in `$HOME/permanent-seeder/settings.toml`. Can you list that folder (`$HOME/permanent-seeder/`)? Is there a settings.toml? or a different .toml file? If you can wipe out that directory so the permanent-seeder can re-create it. That would be something to try.

**Comment by juliangruber** [comment]
```bash
root@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/permanent-seeder# ls
CHANGELOG.md     LICENSE    endpoint-hook.js  node_modules       package.json  settings.toml
CONTRIBUTING.md  README.md  lerna.json        package-lock.json  packages

root@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/permanent-seeder# cat settings.toml 
path = "/root/permanent-seeder"
save_stats = true

[[keys.endpoints]]
url = "http://localhost:3000"
frequency = 5
hook = "/root/permanent-seeder/endpoint-hook.js"
```

Btw I removed the whole `permanent-seeder` folder before trying again.

Another thing that could be a problem: I cloned the repository itself to `~/permanent-seeder`.

**Comment by dpaez** [comment]
> Another thing that could be a problem: I cloned the repository itself to `~/permanent-seeder`.

Yeah, I'm thinking about that. But we only add some specific files, like the different dbs and the settings and hook file. 

I just tried this on my raspberry. I've used the same dir for the cloning `~/permanent-seeder` and it works. So, the only difference up to this point I think is that you are running as root. 🤔

**Comment by juliangruber** [comment]
This happens on a fresh install:

```
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/cli$ ./bin/run config:init
(node:331609) [ENOENT] Error: spawn permanent-seeder ENOENT
```

Full log:

```
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev$ git clone https://github.com/geut/permanent-seeder.git
Cloning into 'permanent-seeder'...
remote: Enumerating objects: 408, done.
remote: Counting objects: 100% (408/408), done.
remote: Compressing objects: 100% (274/274), done.
remote: Total 1615 (delta 248), reused 227 (delta 130), pack-reused 1207
Receiving objects: 100% (1615/1615), 724.53 KiB | 2.05 MiB/s, done.
Resolving deltas: 100% (1050/1050), done.
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev$ cd permanent-seeder/
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder$ npm i

> husky@3.1.0 install /home/ubuntu/dev/permanent-seeder/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@3.1.0 postinstall /home/ubuntu/dev/permanent-seeder/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

added 995 packages from 444 contributors and audited 995 packages in 35.235s

46 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder$ npm run bootstrap

> root@ bootstrap /home/ubuntu/dev/permanent-seeder
> lerna clean && lerna bootstrap

lerna notice cli v3.22.1
PUBLIC_URL=46.101.192.138
lerna info versioning independent
lerna info clean removing /home/ubuntu/dev/permanent-seeder/packages/cli/node_modules
lerna info clean removing /home/ubuntu/dev/permanent-seeder/packages/dashboard/node_modules
lerna info clean removing /home/ubuntu/dev/permanent-seeder/packages/database/node_modules
lerna info clean removing /home/ubuntu/dev/permanent-seeder/packages/sdk/node_modules
lerna info clean removing /home/ubuntu/dev/permanent-seeder/packages/seeder/node_modules
lerna success clean finished
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 5 packages
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder-sdk" package depends on @geut/xd@^1.5.0, which differs from the hoisted @geut/xd@^1.6.0.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on standard@^14.2.0, which differs from the more common standard@^14.3.4.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder" package depends on standard@^14.3.4, which differs from the hoisted standard@^14.2.0.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder-database" package depends on standard@^14.3.4, which differs from the hoisted standard@^14.2.0.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder-core" package depends on standard@^14.3.4, which differs from the hoisted standard@^14.2.0.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder-sdk" package depends on standard@^14.3.1, which differs from the hoisted 
standard@^14.2.0.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder-sdk" package depends on @geut/chan@^2.0.0, which differs from the hoisted @geut/chan@^2.2.1.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder" package depends on jest@^26.1.0, which differs from the hoisted jest@^24.8.0.
lerna WARN EHOIST_PKG_VERSION "@geut/permanent-seeder" package depends on tempy@^0.6.0, which differs from the hoisted tempy@latest.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Finished bootstrapping root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 5 packages
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder$ cd packages/dashboard/
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/dashboard$ cp .env.example .env
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/dashboard$ vim .env
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/dashboard$ npm run build

> @geut/permanent-seeder-dashboard@0.0.1 build /home/ubuntu/dev/permanent-seeder/packages/dashboard
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  240.35 KB  build/static/js/2.14a74649.chunk.js
  9.14 KB    build/static/js/main.2f2008f6.chunk.js
  805 B      build/static/js/runtime-main.8fec6e0f.js

The project was built assuming it is hosted at 46.101.192.138/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  bit.ly/CRA-deploy

ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/dashboard$ cd ../cli
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/cli$ ./bin/run config:init
(node:331609) [ENOENT] Error: spawn permanent-seeder ENOENT
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/cli$ node -v
v10.19.0
ubuntu@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/dev/permanent-seeder/packages/cli$ npm -v
6.14.4
```

**Comment by juliangruber** [comment]
@dpaez @estebanprimost if you want to debug this on the machine, I've added both your public keys:

```bash
ssh ubuntu@46.101.192.138
```

The checkout is in `~/dev`.

**Comment by dpaez** [comment]
This is super handy @juliangruber, thanks!

**Comment by estebanprimost** [comment]
@juliangruber i got permanent-seeder running on `ubuntu` machine with this configs:

`packages/dashboard/.env`
```
PUBLIC_URL=http://46.101.192.138:3001/
```

`~/permanent-seeder/settings.toml`
```
path = "/home/ubuntu/permanent-seeder"
save_stats = true

[[keys.endpoints]]
url = "http://46.101.192.138:8383/modules.json"
frequency = 1
hook = "/home/ubuntu/permanent-seeder/endpoint-hook.js"
```
This key vault endpoint (`http://46.101.192.138:8383/modules.json`) is served via `npm run demo` inside `packages/cli`

Somethings that I've found:
- Node version on `ubuntu` is v10 but we are targetting node v12. For current deploy I just modify conflicted file to get it working.
- `start --restart` is not working properly. A fix will come. You have to make `stop` and `start` as a workaround

Working checkout is in `~/dev/ps-ejp4`

**Comment by juliangruber** [comment]
> @juliangruber i got permanent-seeder running on `ubuntu` machine with this configs:

Awesome, thank you!

> This key vault endpoint (`http://46.101.192.138:8383/modules.json`) is served via `npm run demo` inside `packages/cli`

So if I want to point it to the real vault, I just need to change that url, and to a stop & start?

> * Node version on `ubuntu` is v10 but we are targetting node v12. For current deploy I just modify conflicted file to get it working.

Understood. That would be good to document.

**Comment by estebanprimost** [comment]
> So if I want to point it to the real vault, I just need to change that url, and to a stop & start?

Exactly, you can test now `start --restart` command, it should take new config. Also if you have logs opened in other tab (`logs --live`) you could see new config being applied.

> Understood. That would be good to document.

Yes, thanks, we will add it to docs.

**Comment by juliangruber** [comment]
Thanks so much!
