### ISSUE TITLE
stop command fails

### ISSUE THREAD

**Issue by juliangruber** [geut/permanent-seeder#96]
```bash
root@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/permanent-seeder# ./packages/cli/bin/run stop
(node:327285) Error Plugin: @geut/permanent-seeder: could not find package.json with { type: 'core',
  root: '/root/permanent-seeder/packages/cli',
  name: '@oclif/plugin-update' }
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @geut/permanent-seeder
root: /root/permanent-seeder/packages/cli
See more details with DEBUG=*
(node:327285) Error Plugin: @geut/permanent-seeder: could not find package.json with { type: 'core',
  root: '/root/permanent-seeder/packages/cli',
  name: '@oclif/plugin-warn-if-update-available' }
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @geut/permanent-seeder
root: /root/permanent-seeder/packages/cli
See more details with DEBUG=*
```

```bash
root@permanent-seeder-ubuntu-s-1vcpu-1gb-fra1-01:~/permanent-seeder# DEBUG=* ./packages/cli/bin/run stop
  @oclif/config reading core plugin /root/permanent-seeder/packages/cli +0ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/package.json +0ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/oclif.manifest.json +4ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/.oclif.manifest.json +1ms
  @oclif/config:@geut/permanent-seeder loading IDs from /root/permanent-seeder/packages/cli/src/commands +0ms
  @oclif/config:@geut/permanent-seeder found commands [ 'dashboard',
  'logs',
  'repl',
  'start',
  'status',
  'stop',
  'config:get',
  'config',
  'config:init',
  'key:add',
  'key:get',
  'key',
  'key:remove-all',
  'key:remove' ] +19ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/dashboard.js +5ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/logs.js +172ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/repl.js +9ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/start.js +232ms
  pm2:paths pm2 home resolved to /root/.pm2 /root +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +0ms
  pm2:client Using RPC file /root/.pm2/rpc.sock +0ms
  pm2:client Using PUB file /root/.pm2/pub.sock +0ms
  interactor:client [PING INTERACTOR] Trying to connect to Interactor daemon +0ms
  axon:sock connect attempt null:/root/.pm2/interactor.sock +0ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/status.js +181ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/stop.js +16ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/config/get.js +2ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/config/index.js +2ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/config/init.js +1ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/key/add.js +2ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/key/get.js +173ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/key/index.js +3ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/key/remove-all.js +1ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/key/remove.js +3ms
  @oclif/config reading user plugins pjson /root/.local/share/@geut/permanent-seeder/package.json +0ms
  @oclif/config loadJSON /root/.local/share/@geut/permanent-seeder/package.json +897ms
  axon:sock error ENOENT +213ms
  axon:sock ignored ENOENT +1ms
  @oclif/config loading plugins [ '@oclif/plugin-autocomplete',
  '@oclif/plugin-help',
  '@oclif/plugin-update',
  '@oclif/plugin-warn-if-update-available' ] +6ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/package.json +7ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/package.json +1ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/package.json +0ms
  @oclif/config loadJSON /root/permanent-seeder/packages/cli/package.json +0ms
  @oclif/config loadJSON /root/permanent-seeder/packages/package.json +19ms
  @oclif/config loadJSON /root/permanent-seeder/packages/package.json +1ms
  @oclif/config loadJSON /root/permanent-seeder/packages/package.json +1ms
  @oclif/config loadJSON /root/permanent-seeder/packages/package.json +0ms
  @oclif/config reading core plugin /root/permanent-seeder/node_modules/@oclif/plugin-autocomplete +0ms
  @oclif/config loadJSON /root/permanent-seeder/node_modules/@oclif/plugin-autocomplete/package.json +1ms
  @oclif/config reading core plugin /root/permanent-seeder/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /root/permanent-seeder/node_modules/@oclif/plugin-help/package.json +0ms
  @oclif/config loadJSON /root/permanent-seeder/package.json +1ms
  @oclif/config loadJSON /root/permanent-seeder/package.json +0ms
  @oclif/config loadJSON /root/permanent-seeder/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +2ms
  @oclif/config loadJSON /root/permanent-seeder/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config loadJSON /root/package.json +1ms
  @oclif/config loadJSON /root/package.json +0ms
  @oclif/config loadJSON /package.json +0ms
  @oclif/config loadJSON /package.json +1ms
(node:327324) Error Plugin: @geut/permanent-seeder: could not find package.json with { type: 'core',
  root: '/root/permanent-seeder/packages/cli',
  name: '@oclif/plugin-update' }
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @geut/permanent-seeder
root: /root/permanent-seeder/packages/cli
See more details with DEBUG=*
Error Plugin: @geut/permanent-seeder: could not find package.json with { type: 'core',
  root: '/root/permanent-seeder/packages/cli',
  name: '@oclif/plugin-update' }
    at Plugin.load (/root/permanent-seeder/node_modules/@oclif/config/lib/plugin.js:91:19)
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @geut/permanent-seeder
root: /root/permanent-seeder/packages/cli
See more details with DEBUG=*
(node:327324) Error Plugin: @geut/permanent-seeder: could not find package.json with { type: 'core',
  root: '/root/permanent-seeder/packages/cli',
  name: '@oclif/plugin-warn-if-update-available' }
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @geut/permanent-seeder
root: /root/permanent-seeder/packages/cli
See more details with DEBUG=*
Error Plugin: @geut/permanent-seeder: could not find package.json with { type: 'core',
  root: '/root/permanent-seeder/packages/cli',
  name: '@oclif/plugin-warn-if-update-available' }
    at Plugin.load (/root/permanent-seeder/node_modules/@oclif/config/lib/plugin.js:91:19)
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @geut/permanent-seeder
root: /root/permanent-seeder/packages/cli
See more details with DEBUG=*
  @oclif/config:@oclif/plugin-autocomplete using manifest from /root/permanent-seeder/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /root/permanent-seeder/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +39ms
  @oclif/config start init hook +1ms
  @oclif/config init hook done +1ms
  permanent-seeder init version: @oclif/command@1.8.0 argv: [ 'stop' ] +0ms
  @oclif/config runCommand stop [] +6ms
  @oclif/config:@geut/permanent-seeder require /root/permanent-seeder/packages/cli/src/commands/stop.js +57ms
  @oclif/config start prerun hook +1ms
  @oclif/config prerun hook done +0ms
  permanent-seeder:stop init version: @oclif/command@1.8.0 argv: [] +0ms
  pm2:client [PING PM2] Trying to connect to server +269ms
  axon:sock connect attempt null:/root/.pm2/rpc.sock +51ms
  axon:sock connect +2ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +1ms
  pm2:client Daemon alive +4ms
  axon:sock remove socket 0 +1ms
  pm2:client Launching RPC client on socket file /root/.pm2/rpc.sock +2ms
  axon:sock connect attempt null:/root/.pm2/rpc.sock +1ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +4ms
  pm2:client RPC Connected to Daemon +1ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/root/.pm2/rpc.sock +14ms
  pm2:client Calling stopWatch +6ms
  pm2:client Calling daemon method pm2:stopProcessId on rpc socket:/root/.pm2/rpc.sock +1ms
  pm2:client Calling daemon method pm2:notifyByProcessId on rpc socket:/root/.pm2/rpc.sock +2ms
  axon:sock closing +25ms
  axon:sock closing 1 connections +0ms
  axon:sock remove socket 0 +1ms
  pm2:client PM2 RPC cleanly closed +4ms
  pm2:cli The session lasted 0.035s +0ms
  @oclif/config start postrun hook +38ms
  @oclif/config postrun hook done +1ms
  axon:sock attempting reconnect +24ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +1ms
  interactor:client Interactor Daemon not launched +325ms
  axon:sock connect attempt null:/root/.pm2/interactor.sock +0ms
  axon:sock error ENOENT +1ms
  axon:sock ignored ENOENT +0ms
```

**Comment by dpaez** [comment]
Oh. I think I know the problem. I've added a new oclif plugin that checks for updates and since we didn't publish anything yet it might be causing this output.

**Comment by dpaez** [comment]
@juliangruber https://github.com/geut/permanent-seeder/pull/97 is a possible fix. I tried to quickly disable the plugins. If you have the chance to try this branch sometime, it would be good. Thanks 👍
